# .air.toml
[build]
bin = "main"
cmd = "go build -buildvcs=false -o main ."
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp"]
exclude_file = ["air.toml", "go.sum", "go.mod"]
main = "main.go"

[log]
level = "debug"
