version: '3.8'

services:
  keycloak:
    image: "quay.io/keycloak/keycloak:21.1.1"
    command:
      - start-dev
      - --health-enabled=true
      - --import-realm
    # volumes:
    #   - keycloak_data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'

  postgres:
    image: postgres:13
    container_name: deals_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deals
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deals_app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: deals
      KEYCLOAK_URL: http://keycloak:8080
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - keycloak
    volumes:
      - .:/app
    command: ["air"]

volumes:
  postgres_data:
