version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: deals_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deals
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deals_app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: deals
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["air"]

volumes:
  postgres_data:
